# Generated by Django 5.2.14 on 2026-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(default='🎵', max_length=10)),
                ('category', models.CharField(choices=[('string', 'Cuerda'), ('percussion', 'Percusión'), ('wind', 'Viento'), ('voice', 'Voz'), ('keyboard', 'Teclado')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instruments/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
