# Generated by Django 5.2.14 on 2026-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('days', models.JSONField(default=list, help_text='Lista de días (0=Lunes...6=Domingo)')),
                ('message', models.CharField(default='¡Es hora de practicar! 🎵', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recordatorio',
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('exercises_done', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('accuracy_avg', models.FloatField(blank=True, null=True)),
                ('practice_minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Registro de progreso',
                'ordering': ['-date'],
            },
        ),
    ]
