# Generated by Django 5.2.14 on 2026-05-15 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento de ejercicio',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exercise_type', models.CharField(choices=[('note_recognition', 'Reconocimiento de notas'), ('rhythm', 'Ritmo'), ('chord', 'Acordes'), ('pitch', 'Afinación'), ('sight_reading', 'Lectura musical'), ('ear_training', 'Entrenamiento auditivo')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='easy', max_length=10)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list, help_text='Lista de opciones para ejercicios de selección múltiple')),
                ('correct_answer', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=25)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='exercises/audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['difficulty', 'exercise_type'],
            },
        ),
    ]
