# Generated by Django 5.2.14 on 2026-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('audio', 'Análisis de audio'), ('performance', 'Análisis de desempeño'), ('recommendation', 'Recomendación')], max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ai/audio/')),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('pitch_accuracy', models.FloatField(blank=True, null=True)),
                ('rhythm_accuracy', models.FloatField(blank=True, null=True)),
                ('detected_notes', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('feedback_text', models.TextField(blank=True)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Análisis de IA',
                'verbose_name_plural': 'Análisis de IA',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('priority', models.PositiveIntegerField(default=5)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recomendación',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
