from django.db import models
from django.conf import settings


class AIAnalysis(models.Model):
    """Stores AI performance analysis results (HU-011)."""
    ANALYSIS_TYPE_CHOICES = [
        ("audio", "Análisis de audio"),
        ("performance", "Análisis de desempeño"),
        ("recommendation", "Recomendación"),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="ai_analyses")
    analysis_type = models.CharField(max_length=20, choices=ANALYSIS_TYPE_CHOICES)
    exercise = models.ForeignKey(
        "exercises.Exercise", null=True, blank=True,
        on_delete=models.SET_NULL, related_name="ai_analyses"
    )

    # Input data
    audio_file = models.FileField(upload_to="ai/audio/", null=True, blank=True)
    input_data = models.JSONField(default=dict, blank=True)

    # Results
    accuracy_score = models.FloatField(null=True, blank=True)
    pitch_accuracy = models.FloatField(null=True, blank=True)
    rhythm_accuracy = models.FloatField(null=True, blank=True)
    detected_notes = models.JSONField(default=list, blank=True)
    strengths = models.JSONField(default=list, blank=True)
    weaknesses = models.JSONField(default=list, blank=True)
    recommendations = models.JSONField(default=list, blank=True)
    feedback_text = models.TextField(blank=True)
    raw_result = models.JSONField(default=dict, blank=True)

    analyzed_at = models.DateTimeField(auto_now_add=True)
    processing_time_ms = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "Análisis de IA"
        verbose_name_plural = "Análisis de IA"
        ordering = ["-analyzed_at"]

    def __str__(self):
        return f"{self.user} — {self.get_analysis_type_display()} {self.analyzed_at.strftime('%d/%m/%Y')}"


class UserRecommendation(models.Model):
    """Personalized recommendations generated by AI (HU-011, HU-028)."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="recommendations")
    lesson = models.ForeignKey("lessons.Lesson", null=True, blank=True, on_delete=models.SET_NULL)
    exercise = models.ForeignKey("exercises.Exercise", null=True, blank=True, on_delete=models.SET_NULL)
    reason = models.TextField()
    priority = models.PositiveIntegerField(default=5)
    is_seen = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Recomendación"
        ordering = ["priority", "-created_at"]

    def __str__(self):
        return f"Rec → {self.user}: {self.reason[:60]}"
