# Generated by Django 5.2.14 on 2026-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=15)),
                ('lesson_type', models.CharField(choices=[('theory', 'Teoría'), ('practice', 'Práctica'), ('tutorial', 'Tutorial')], default='theory', max_length=15)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(help_text='Contenido en Markdown')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube o Vimeo')),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['instrument', 'level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lección de usuario',
            },
        ),
    ]
